wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lounge Fallback Hotspot"
    password: ${esphome_fallback_wifi_password}

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encrypt}
ota:
  - platform: esphome
    password: ${esphome_password}

captive_portal:

# Enable logging
logger: