substitutions:
  <<: !include secrets.yaml

esphome:
  name: living-room
  platform: ESP8266
  board: nodemcuv2

<<: !include components/core.yaml

i2c:
  scan: True

light:
  - platform: rgb
    name: "Living Rooom RGB Led"
    red: output_component_red
    green: output_component_green
    blue: output_component_blue
    restore_mode: ALWAYS_OFF

output:
  - platform: esp8266_pwm
    id: output_component_red
    pin: D6
    
  - platform: esp8266_pwm
    id: output_component_green
    pin: D7
    
  - platform: esp8266_pwm
    id: output_component_blue
    pin: D8

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

  - platform: uptime
    name: "Living Room Uptime"
    
  - platform: wifi_signal
    name: "Living Room WiFi Signal"
    update_interval: 60s
switch:
  - platform: restart
    name: "Living Room Restart"
